### ISSUE TITLE
(Wrong) Date Error in Drop History

### ISSUE THREAD

**Issue by bencentra** [ComputerScienceHouse/Drink-JS#41] opened 2012-02-19 09:59 UTC
Except a drop from Snack, it claims all of my drinks were dropped on 2011-10-22 22:48:41. That doesn't sound right.

**Comment by seanmcgary** [comment] 2012-02-19 22:59
So this is actually not a bug. The reason your history only goes back to October is because the new drink server is running on a new database and the old data simply has yet to be migrated over. Once that happens, you will see EVERY drop youve ever made. Since this doesnt effect the runtime of the server, Im going to close this and make a new issue to migrate the old database over.

**Closed as completed by seanmcgary** 2012-02-19 22:59 UTC
Labels: Bug
